export const ac = {
    R_A_S: "RESIZE_AUTH_SCREEN",
    R_D_S: "RESIZE_DASHBOARD_SCREEN",
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    SU_S_N: "SIGNUP_SET_NAME",
    SU_S_E: "SIGNUP_SET_EMAIL",
    SU_S_P: "SIGNUP_SET_PASSWORD",
    SU_S_CP: "SIGNUP_SET_CONFIRM_PASSWORD",
    SU_SUB: "SIGNUP_SUBMIT",
    LI_S_E: "LOGIN_SET_EMAIL",
    LI_S_P: "LOGIn_SET_PASSWORD",
    LI_SUB: "LOGIN_SUBMIT"
}